//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demkaKursVersion2
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationCompetition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegistrationCompetition()
        {
            this.Awarding = new HashSet<Awarding>();
        }
    
        public int ID { get; set; }
        public int ID_Competitions { get; set; }
        public int ID_CategoriesSports { get; set; }
        public int ID_Sportsmen { get; set; }
        public int ID_Trainer { get; set; }
        public System.DateTime DataRegistration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Awarding> Awarding { get; set; }
        public virtual CategoriesSports CategoriesSports { get; set; }
        public virtual Competitions Competitions { get; set; }
        public virtual Sportsmen Sportsmen { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
