//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demkaKursVersion2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecificationsInfrastructure
    {
        public int ID_Infrastructure { get; set; }
        public int ID_Specifications { get; set; }
        public string Value { get; set; }
    
        public virtual Infrastructure Infrastructure { get; set; }
        public virtual Specifications Specifications { get; set; }
    }
}
