//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demkaKursVersion2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypesSports_Sportsmen
    {
        public int Sportsmen_ID { get; set; }
        public int Types_Sports_ID { get; set; }
        public Nullable<int> Class { get; set; }
    
        public virtual Sportsmen Sportsmen { get; set; }
        public virtual TypesSports TypesSports { get; set; }
    }
}
